name: Birthday Check

on:
  schedule:
    - cron: '5 0 * * *'  # Runs every day at midnight UTC

jobs:
  check_birthdays:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run birthday check script
      run: |
        python main.py
